# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bold #cba6f7)  $directory $git_branch
[❯](bold #89b4fa) """

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)[❯](bold blue)[❯](bold orange)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = "[](bold #cba6f7) [❯](bold #89b4fa)[❯](bold #eba0ac) [$branch](bold #eba0ac)"

[directory]
format = "[$path](#eba0ac)"
