#! /bin/sh

xsetroot -cursor_name left_ptr &
nitrogen --restore

sxhkd & 
bspc monitor -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap 0

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config focused_border_color "#585b70"
bspc config normal_border_color "#313244"
