[colors.primary] 
background='#0f1417'
foreground='#dfe3e7'

[colors.cursor] 
text='#dfe3e7'
cursor='#c0c7cd'

[colors.vi_mode_cursor]
text='#0f1417'
cursor='#8dcff1'

[colors.search.matches]
foreground='#40484c'
background='#c8c2ea'

[colors.search.focused_match]
foreground='#40484c'
background='#8dcff1'

[colors.footer_bar]
foreground='#40484c'
background='#dfe3e7'

[colors.hints.start]
foreground='#40484c'
background='#b5cad6'

[colors.hints.end]
foreground='#40484c'
background='#b5cad6'

[colors.selection]
text='#0f1417'
background='#8dcff1'


[colors.normal]
black='#0f1417'
red='#ffb4ab'
green='#8dcff1'
yellow='#166684'
blue='#8dcff1'
magenta='#c8c2ea'
cyan='#b5cad6'
white='#dfe3e7'


[colors.bright]
black='#585B70'
red='#F38BA8'
green='#A6E3A1'
yellow='#F9E2AF'
blue='#89B4FA'
magenta='#F5C2E7'
cyan='#94E2D5'
white='#A6ADC8'


[colors.dim]
black='#45475A'
red='#F38BA8'
green='#A6E3A1'
yellow='#F9E2AF'
blue='#89B4FA'
magenta='#F5C2E7'
cyan='#94E2D5'
white='#BAC2DE'
